# Generated by Django 4.0.6 on 2022-07-30 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre del director', max_length=64)),
                ('surname', models.CharField(help_text='Apellidos del director', max_length=64)),
                ('born', models.DateField()),
                ('die', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titulo del libro', max_length=32)),
                ('summary', models.TextField(help_text='De qué es el libro', max_length=128)),
                ('release', models.DateField()),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates.director')),
            ],
        ),
    ]
