# Generated by Django 4.0.6 on 2022-07-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='die',
            field=models.DateField(null=True),
        ),
    ]
