# Generated by Django 4.0.6 on 2022-07-31 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_director_die'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.director'),
        ),
        migrations.AlterField(
            model_name='films',
            name='summary',
            field=models.TextField(help_text='De qué es la pelicula', max_length=400),
        ),
        migrations.AlterField(
            model_name='films',
            name='title',
            field=models.CharField(help_text='Titulo de la pelicula', max_length=32),
        ),
    ]
